---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
implicit:
  - Личные данные пользователей надёжно защищены от кражи
  - Интерфейс сайта должен быть удобным и интуитивно понятным пользователям
  - Интерфейс сайта должен быть достаточно эстетичным
  - Вёрстка должна быть ровной и аккуратной
  - Шрифт должен быть читаемым для большинства пользователей - достаточно большим и контрастным
  - Сайт должен реагировать на действия пользователя достаточно быстро - не дольше 1 секунды
  - Все товары на сайте должны иметь ценники, цена должна быть положительным числом долларов точностью до сотых долей 
  - Товары на сайте должны соответствовать указанным категориям
  - Описания, фотографии и категории товаров должны быть указаны достаточно подробно, не должны содержать ошибок и дезинформации; быть на языке, выбранном пользователем (из представленных на сайте)
  - Информация на сайте не должна нарушать законы об авторском праве
  - На сайте могут продаваться только товары, разрешённые к продаже через Интернет и конкретно через этот сайт
  - Сайт должен функционировать согласно законам страны, в которой он используется
  - Товары, продаваемые на сайте, должны иметь корректную дату годности - на сайте не должны продаваться товары с истёкшим сроком годности
  - Итоговая сумма в корзине должна считаться корректно - как сумма цен всех добавленных товаров
  - Содержимое корзины должно сохраняться и восстанавливаться при перезагрузке страинцы
